backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/markdown-pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "URL Path", name: "path", widget: "string", default: "/blog/" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
